site_name: FAIR training SOP
site_url: 
nav:
    - Home: index.md
    - FAIR principles (notes): fair.md
    - Materials: materials.md
    - Events: events.md
    - Workflows: workflows.md
theme: readthedocs

